language: java
  
  deploy:
   edge: true
   provider: cloudfoundry
   username: contactgladius@gmail.com
   password: anandhi123
   api: https://api.run.pivotal.io
   organization: vecinnovators
   space: staging
